---
title: "Future Exercise"
---

```{r}
library("dslabs")
str(gapminder)
summary(gapminder)
data(gapminder)

africadata <- subset(gapminder, (continent == "Africa"))
#creates a new dataframe from a subset of the old one where the continent is Africa
str(africadata)
#Checks to make sure I have the correct number of observations

inf_LE <- data.frame(africadata$infant_mortality, africadata$life_expectancy)
#creates a new dataframe from these two columns of the africadata dataframe
#this one is for infant mortality and Life expectancy
str(inf_LE)
#This checks to make sure I got it right

pop_LE <- data.frame(africadata$population, africadata$life_expectancy)
#This creates a new dataframe for population and life expectancy data
str(pop_LE)
#This checks that I have everything right

plot(inf_LE)
#plots this dataframe on a scatter plot
#plot(pop_LE$africadata.population, pop_LE$africadata.life_expectancy, log = "x")
#above is one option for generating the other scatter plot
plot(pop_LE, log = "x")
#here is a neater version
#the log function is where you can specify which axis should be in log, in this case population
```
My hypothesis for the streaks of data we see is that they are individual countries over time
```{r}
year_inf <- data.frame(africadata$year, africadata$infant_mortality)
#this creates a matrix with year and infant mortality
year_inf[is.na(year_inf)] <- "A"
#this line rewrites the dataset, changing all NA's to A
missing <- subset(year_inf, (africadata.infant_mortality == "A"))
#this makes a new dataset with the subset function that pulls out all the years with A as a value
#This didn't work with NA which is why I changed it to A. Not the most elegant solution but it works
str(missing)
#this line is for checking

year2000 <- subset(africadata, (year == "2000"))
#this creates a new data.frame with all the data from the year 2000 from africadata
str(year2000)
#this is for checking

plot(year2000$infant_mortality, year2000$life_expectancy)

plot(year2000$population, year2000$life_expectancy, log = "x")
```
